---
title: "0428실습"
author: "LeeJunHyoung"
date: '2021 4 25 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
help <- read.csv("C:/석사자료/석사수업자료/2021-1학기/통계소프트웨어실습조교/help.csv", header=T)
head(help)
```

```{r}
library(mosaic)
favstats(help$age, data=help) # proc univariate과 유사
```

```{r}
library(moments)
skewness(help$age)
kurtosis(help$age)
mean(help$age, trim=0.1) # 양 쪽을 10%씩 자르고 평균 계산
```

```{r}
quantile(help$age, c(0.025,0.975))
quantile(help$age, seq(from=0.95, to=0.975, by=0.0125))
```

```{r}
x <- scale(help$age)
head(x) # 데이터 셋에서 추출했기 때문에 1열의 형태로 나옴
y <- (help$age-mean(help$age))/sd(help$age)
head(y) # 데이터값을 추출해 나열한 것이기 때문에 일렬로 나옴
```

```{r}
tcrit <- qt(0.975, df=length(help$age)-1)
mean(help$age) + c(-tcrit,tcrit)*sd(help$age)/sqrt(length(help$age))
t.test(help$age)$conf.int
```

```{r}
# 이항분포로부터 p-value를 구하는 exact test.
binom.test(x=490, n=1000, p=0.5, alternative = "two.sided")
# 귀무가설(H0) : 동전의 앞면이 나올 확률은 0.5이다. vs 대립가설(H1) : 0.5가 아니다.
# 검정결과 : (검정통계량)p = 0.548(> 0.05)이 나오므로 귀무가설을 기각하지 못함.
# 즉 p-value가 0.05보다 크므로 귀무가설을 기각하지 못하므로 동전의 앞면이 나올 확률은 0.5이다.

# 정규분포를 띄는 모집단에서의 모비율에 대한 검정
prop.test(x=480, n=1000, p=0.5, alternative = "two.sided", conf.level = 0.95)
# 귀무가설(H0) : 동전의 앞면이 나올 확률은 0.5이다. vs 대립가설(H1) : 0.5가 아니다.
# 검정결과 : p = 0.2175(> 0.05)가 나오므로 귀무가설을 기각하지 못함.
# 유의수준 5%에서 귀무가설을 기각하지 못하여 동전의 앞면이 나올 확률은 0.5이다.
# p의 95% 신뢰구간은 (0.4486, 0.5114) 이다.




```

