---
title: "201800697_김민지 0602"
output: html_document
editor_options: 
  chunk_output_type: console
---

# 1번. 교배실험 결과가 멘델 법칙을 따르는지?
```{r}
beans=c(306,104)
chisq.test(beans,p=c(3/4,1/4))
```
* 검정방법 : 적합도 검정 (카이제곱분포)
* H0:교배실험 결과가 멘델 법칙을 잘 따른다. H1:교배실험 결과가 멘델 법칙을 잘 따르고 있지 않다.
* p-value = 0.8642 검정통계량: x-squared=0.029268 (자유도df=1)
* 0.8642>0.05 이기 때문에 귀무가설을 기각하지 못하고, 귀무가설을 채택한다.
* 즉, 교배실험 결과가 멘델 법칙을 잘 따른다.

# 2. 운동을 잘하는 것과 학업성적이 관련이 있는지 검정
```{r}
dat2=rbind(c(3,2,5),c(26,10,4),c(5,20,5))
rownames(dat2)=c("상","중","하")
colnames(dat2)=c("상","중","하")
chisq.test(dat2)
```
* 검정방법 : 독립성 검정
* H0:운동을 잘하는 것과 학업성적이 관련이 없다. H1:운동을 잘하는 것과 학업성적은관련이 있다.
* p-value:3.538e-05 검정통계량: x-squared=25.76(자유도df=4)
* 3.538e-05<0.05 이기 때문에 귀무가설을 기각한다. 
* 즉, 학생들이 운동을 잘하는 것과 학업성적에는 관련이 있다.

# 3.남녀 간의 만족도에 차이가 있는지 검정
```{r}
dat3=rbind(c(15,4,1),c(10,8,2))
rownames(dat3)=c("남","여")
colnames(dat3)=c("만족","보통","불만족")
chisq.test(dat3)
```
* 검정방법 : 동일성 검정
* H0:남녀 간의 만족도에 차이가 없다. H1:남녀 간의 만족도에 차이가 있다.
* p-value=0.2636 검정통계량: x-squared=2.6667(자유도df=2)
* 0.2636>0.01 이기 때문에 귀무가설을 기각하지 못한다. 따라서 귀무가설을 채택한다.
* 즉, 남녀 간의 만족도에는 차이가 없다.
